export const LANGUAGE_OPTIONS = [
  ["en", "English"],
  ["he", "עברית"],
  ["ar", "العربية"],
  ["es", "Español"],
  ["fr", "Français"],
  ["de", "Deutsch"],
  ["it", "Italiano"],
  ["pt", "Português"],
  ["pt-BR", "Português (Brasil)"],
  ["ru", "Русский"],
  ["uk", "Українська"],
  ["pl", "Polski"],
  ["nl", "Nederlands"],
  ["tr", "Türkçe"],
  ["el", "Ελληνικά"],
  ["hi", "हिन्दी"],
  ["zh-CN", "中文（简体）"],
  ["zh-TW", "中文（繁體）"],
  ["ja", "日本語"],
  ["ko", "한국어"],
  ["vi", "Tiếng Việt"],
  ["th", "ไทย"],
  ["id", "Bahasa Indonesia"],
  ["sv", "Svenska"],
  ["da", "Dansk"],
  ["no", "Norsk"],
  ["fi", "Suomi"],
  ["cs", "Čeština"],
  ["ro", "Română"],
  ["hu", "Magyar"],
] as const;
