import { useCallback, useState } from 'react';
import { Link } from 'react-router-dom';
import { z } from 'zod';
import { BookOpenText, Sparkles } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { RemoteState } from '../components/RemoteState';
import { errorMessage, intent, page, product, query, readingPreview, readingSchema, readingSummary, uuid, type Intent, type Reading } from '../lib/product';
import { useResource } from '../lib/useResource';
import { textSegments } from '../lib/reading';
export function LiveReadingPage() {
  const { profile } = useApp(); const [topic, setTopic] = useState(profile.interests[0] || ''); const [language, setLanguage] = useState(profile.languages[0]?.languageCode || 'en'); const [level, setLevel] = useState(''); const [length, setLength] = useState('short'); const [contentType, setContentType] = useState('article');
  const [preview, setPreview] = useState<z.infer<typeof readingPreview>>(); const [reading, setReading] = useState<Reading>(); const [pending, setPending] = useState<Intent>();
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [cursor, setCursor] = useState<string>();
  const historyUrl = `reading${query({ limit: '10', cursor })}`; const history = useResource(useCallback(() => product(page(readingSummary), historyUrl), [historyUrl]));
  const generate = async () => { setBusy(true); setError(''); setReading(undefined); setPreview(undefined); setPending(undefined); try { const result = await product(readingPreview, 'reading/preview', 'POST', { targetLanguageCode: language, ...(topic.trim() ? { topic } : {}), ...(level ? { requestedLevel: level } : {}), contentType, lengthPreset: length }); setPreview(result); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  const open = async () => { if (!preview || busy) return; setBusy(true); setError(''); const submission = pending || intent({ publicationToken: preview.publicationToken }); setPending(submission); try { const result = await product(z.object({ reading: readingSchema }), 'reading', 'POST', submission.body, submission.eventId); setReading(result.reading); setPreview(undefined); setPending(undefined); await history.reload(); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  const view = async (id: string) => { setBusy(true); setError(''); try { const result = await product(z.object({ reading: readingSchema }), `reading/${id}`); setReading(result.reading); setPreview(undefined); setPending(undefined); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  const remove = async (id: string) => { if (!window.confirm('להסיר את הקריאה מההיסטוריה? היסטוריית התרגול תישמר.')) return; setBusy(true); setError(''); try { await product(z.object({ id: uuid }), `reading/${id}`, 'DELETE'); if (reading?.id === id) setReading(undefined); await history.reload(); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } };
  return <div className="reading-page live-page page-enter"><section className="page-heading-row"><div><p className="eyebrow">מילים שחיות בתוך סיפור</p><h1>קריאה בהקשר</h1><p>קטע אישי שמשלב מילים מהתור שלך, בשפת הלימוד ובגובה העיניים.</p></div><BookOpenText size={36} /></section><div className="live-two-columns"><section className="live-panel form-stack"><h2>מה נרצה לקרוא?</h2><fieldset disabled={busy || !!pending} className="plain-fieldset form-stack"><label className="field"><span>נושא — רשות</span><input maxLength={500} value={topic} onChange={e => setTopic(e.target.value)} placeholder="השרת יבחר מתוך תחומי העניין אם יישאר ריק" /></label><label className="field"><span>שפת הלימוד — קוד BCP-47</span><input maxLength={64} dir="ltr" value={language} onChange={e => setLanguage(e.target.value)} /></label><div className="live-form-grid"><label className="field"><span>רמת הקריאה</span><select value={level} onChange={e => setLevel(e.target.value)}><option value="">הרמה האפקטיבית מהשרת</option>{['A1', 'A2', 'B1', 'B2', 'C1', 'C2'].map(l => <option key={l}>{l}</option>)}</select></label><label className="field"><span>אורך</span><select value={length} onChange={e => setLength(e.target.value)}><option value="short">קצר</option><option value="medium">בינוני</option><option value="long">ארוך</option></select></label></div><label className="field"><span>סוג תוכן</span><select value={contentType} onChange={e => setContentType(e.target.value)}>{Object.entries({ article: 'מאמר', story: 'סיפור', essay: 'מסה', news_style: 'בסגנון חדשות', other: 'אחר' }).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><button className="button primary" disabled={!language.trim()} onClick={() => void generate()}><Sparkles size={17} />{busy ? 'מכין…' : 'יצירת תצוגה מקדימה'}</button></fieldset><p className="muted-note">אם לא הוגדר ספק קריאה בשרת, יצירת תוכן לא תהיה זמינה. לא מוצגים טקסטים מדומים לחשבון אמיתי.</p></section><section className="live-panel"><h2>היסטוריית הקריאה</h2><RemoteState loading={history.loading} error={history.error} retry={() => void history.reload()} />{history.data?.items.map(r => <div className="live-toolbar" key={r.id}><button className="button ghost" disabled={busy} onClick={() => void view(r.id)}>{r.title}</button><small>{r.targetLanguageCode} · {new Date(r.openedAt).toLocaleDateString('he-IL')}</small><button className="button ghost danger-text" disabled={busy} onClick={() => void remove(r.id)}>הסרה</button></div>)}{history.data && !history.data.items.length && <p>קטעים שפתחתם יופיעו כאן.</p>}{history.data?.nextCursor && <button className="button ghost" onClick={() => setCursor(history.data!.nextCursor!)}>קטעים נוספים</button>}</section></div>{error && <p className="form-error" role="alert">{error}</p>}
  {preview && <section className="live-panel"><p className="eyebrow">מוכן לפתיחה</p><h2>{preview.reading.title}</h2><p>{preview.reading.targets.length} מילים · {preview.reading.effectiveLevel || 'רמה לא הוגדרה'} · {preview.provider.name}</p><small>תקף עד {new Date(preview.expiresAt).toLocaleTimeString('he-IL')}</small><p>הטקסט ייפתח ויירשם בהיסטוריה רק בלחיצה הבאה.</p><button className="button primary" disabled={busy} onClick={() => void open()}>{pending ? 'ניסיון נוסף לאותה פתיחה' : 'פתיחת הקטע'}</button></section>}
  {reading && <article className="live-panel live-reading"><p className="eyebrow">{reading.targetLanguageCode} · {reading.effectiveLevel || 'ללא רמה'}</p><h2 dir="auto">{reading.title}</h2><div className="live-reading-body" dir="auto" lang={reading.targetLanguageCode}>{textSegments(reading).map((segment, index) => segment.itemId ? <Link className="reading-word" key={index} to={`/vocabulary?item=${segment.itemId}`} title="פתיחת פרטי המילה">{segment.text}</Link> : <span key={index}>{segment.text}</span>)}</div><p>עצם הקריאה אינה מעלה שליטה או XP.</p><Link className="button primary" to={`/learn/session/article_quiz?reading=${reading.id}`}>תרגול המילים מתוך הקטע</Link></article>}</div>;
}
